services:
  - type: web
    name: acuar-io
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 2 -b 0.0.0.0:$PORT app:app
    envVars:
      - key: DB_DIR
        value: /var/data
      - key: SECRET_KEY
        generateValue: true
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
