# Generated by Django 5.2.17 on 2026-09-27 19:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MaintenanceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="fecha",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("water_change", "Cambio de agua"),
                            ("dosing", "Dosificación"),
                            ("livestock", "Fauna / corales"),
                            ("equipment", "Equipo"),
                            ("cleaning", "Limpieza"),
                            ("other", "Otro"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="categoría",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="título")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="registrado"),
                ),
            ],
            options={
                "verbose_name": "entrada del diario",
                "verbose_name_plural": "diario de mantenimiento",
                "ordering": ["-occurred_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Parameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Nombre corto, p. ej. KH.",
                        max_length=20,
                        unique=True,
                        verbose_name="código",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="nombre")),
                (
                    "unit",
                    models.CharField(blank=True, max_length=20, verbose_name="unidad"),
                ),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("physical", "Físicos"),
                            ("major", "Mayoritarios"),
                            ("nutrient", "Nutrientes"),
                            ("custom", "Otros"),
                        ],
                        default="custom",
                        max_length=20,
                        verbose_name="grupo",
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="mínimo objetivo",
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=10,
                        null=True,
                        verbose_name="máximo objetivo",
                    ),
                ),
                (
                    "decimals",
                    models.PositiveSmallIntegerField(
                        default=2, verbose_name="decimales a mostrar"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=100, verbose_name="orden"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="activo")),
                (
                    "is_predefined",
                    models.BooleanField(
                        default=False, editable=False, verbose_name="predefinido"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="descripción"),
                ),
            ],
            options={
                "verbose_name": "parámetro",
                "verbose_name_plural": "parámetros",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Measurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4, max_digits=10, verbose_name="valor"
                    ),
                ),
                (
                    "measured_at",
                    models.DateTimeField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="fecha de medición",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Manual"),
                            ("kh_guardian", "KH Guardian"),
                            ("other", "Otro dispositivo"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="origen",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="notas")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="registrado"),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="measurements",
                        to="aquarium.parameter",
                        verbose_name="parámetro",
                    ),
                ),
            ],
            options={
                "verbose_name": "medición",
                "verbose_name_plural": "mediciones",
                "ordering": ["-measured_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["parameter", "-measured_at"],
                        name="measurement_param_date",
                    )
                ],
            },
        ),
    ]
